export const teamCatalog = {
  'Produção': [
    ['Acleston Ricardo Pereira dos Santos', ''],
    ['Alecsandro do Nascimento Barbosa', 'ALECSANDRO DO NASCIMENTO BARBOSA'],
    ['Anival Bento da Silva', 'GESSE MESSIAS PIMENTEL MONTEIRO'],
    ['Apoio', ''],
    ['Arlindo Custodio da Anunciação', 'ARLINDO CUSTODIO DA ANUNCIAÇÃO'],
    ['Asfalto', ''],
    ['Asfalto II', ''],
    ['Canteiro ETE', 'RIVALDO SEBASTIAO DA SILVA'],
    ['Canteiro Serra', ''],
    ['Canteiro Vila Velha', ''],
    ['Cisaro Mendes Gonçalves', 'CISARO MENDES GONÇALVES'],
    ['Cleverton Almeida Santos', 'CLEVERTON ALMEIDA SANTOS'],
    ['Fabio Alvarenga da Silva', 'FABIO ALVARENGA DA SILVA'],
    ['Gilson Raimundo Ferreira', 'GILSON RAIMUNDO FERREIRA'],
    ['Guilherme de Jesus Santos', 'GUILHERME DE JESUS SANTOS'],
    ['Jocimar Pereira Correa', ''],
    ['Juvenil Galdino Batista', 'JUVENIL GALDINO BATISTA'],
    ['Limpeza', ''],
    ['Loteamento', 'EDILSON DOS SANTOS'],
    ['Marconi Modesto da Silva', ''],
    ['Missinio dos Santos', ''],
    ['Olivan Silva Nascimento', 'OLIVAN SILVA NASCIMENTO'],
    ['Paulo Cesar Goncalves', 'PAULO CESAR GONCALVES'],
    ['Pavimentação', ''],
    ['Reinaldo Andre dos Santos', 'REINALDO ANDRE DOS SANTOS'],
    ['Reparos', ''],
    ['Sidenilson Santos Vieira', 'SIDENILSON SANTOS VIEIRA'],
    ['Thiago Luis Silva Lima', 'THIAGO LUIS SILVA LIMA'],
    ['Uanderson Soares de Souza', 'UANDERSON SOARES DE SOUZA'],
    ['Wesley Soares Torres', ''],
    ['Wilson Nogueira da Silva', 'WILSON NOGUEIRA DA SILVA'],
  ],
  'Suporte Operacional': [
    ['Aguimaraes Souza dos Santos', 'AGUIMARAES SOUZA DOS SANTOS'],
    ['Alecsandro do Nascimento Barbosa', ''],
    ['Anival Bento da Silva', ''],
    ['Apoio', ''],
    ['Arlindo Custodio da Anunciação', ''],
    ['Asfalto', ''],
    ['Asfalto II', ''],
    ['Caixas', ''],
    ['Canteiro Cariacica', ''],
    ['Canteiro ETE', ''],
    ['Canteiro Serra', ''],
    ['Canteiro Vila Velha', ''],
    ['Fabio Alvarenga da Silva', ''],
    ['Gilson Raimundo Ferreira', ''],
    ['Jocimar Pereira Correa', 'JOCIMAR PEREIRA CORREA'],
    ['Limpeza', ''],
    ['Marconi Modesto da Silva', ''],
    ['Missinio dos Santos', 'MISSINIO DOS SANTOS'],
    ['Munck', ''],
    ['Olivan Silva Nascimento', ''],
    ['Reinaldo Andre dos Santos', ''],
    ['Reparos', ''],
    ['Sidenilson Santos Vieira', ''],
    ['Thiago Luis Silva Lima', ''],
    ['Vistoria', ''],
    ['Wilson Nogueira da Silva', ''],
  ],
};
