import fs from 'node:fs';
import {isDeepStrictEqual} from 'node:util';
import {teamCatalog} from './revisedGroupTeamsCatalog.mjs';
import {initializeApp,deleteApp} from 'firebase/app';
import {getFirestore,doc,runTransaction,getDocFromServer} from 'firebase/firestore';
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
const d=JSON.parse(fs.readFileSync('group-teams-current.local','utf8'));
const group=d.companyGroups.find(g=>norm(g.name)==='grupo macro');if(!group)throw new Error('Grupo ausente');
teamCatalog[Object.keys(teamCatalog).find(k=>norm(k)==='producao')].push(['Caixas','']);
const now=new Date().toISOString();const changes=new Map();
function set(c,id,patch){const before=d[c].find(x=>x.id===id)||null;const prev=changes.get(c+'/'+id)?.after||before||{id,createdAt:now};const after={...prev,...patch,updatedAt:now};const comparable={...after};delete comparable.updatedAt;const original={...before};delete original.updatedAt;if(isDeepStrictEqual(comparable,original))return;changes.set(c+'/'+id,{collection:c,id,before,after});}
function del(c,id){const before=d[c].find(x=>x.id===id);if(before)changes.set(c+'/'+id,{collection:c,id,before,after:null});}
const employees=d.employees.filter(e=>e.groupId===group.id||(!e.groupId&&d.companyGroupCompanies.some(c=>c.groupId===group.id&&c.companyId===e.companyId)));
const units=d.companyGroupUnits.filter(u=>u.groupId===group.id);
const targets=[];
for(const [department,rows]of Object.entries(teamCatalog))for(const[name,leaderName]of rows){const deps=units.filter(u=>u.type==='department'&&u.active!==false&&norm(u.name)===norm(department));if(deps.length!==1)throw new Error('Departamento ambiguo');const matches=units.filter(u=>u.type==='team'&&u.id.startsWith('managed-team-')&&norm(u.name)===norm(name)&&(u.parentUnitId===deps[0].id||name==='Caixas'));if(matches.length!==1)throw new Error('Equipe alvo ambigua: '+name);const unit=matches[0];const sourceId='source-'+unit.id;if(!d.teams.some(t=>t.id===sourceId))throw new Error('Origem ausente');const leaders=leaderName?employees.filter(e=>norm(e.name)===norm(leaderName)&&e.status!=='terminated'):[];if(leaderName&&leaders.length!==1)throw new Error('Encarregado ambiguo: '+leaderName);const owner=leaders[0]?.id||'';set('companyGroupUnits',unit.id,{active:true,coordinatorEmployeeId:owner,parentUnitId:deps[0].id,name});targets.push({id:unit.id,sourceId,name,department,departmentUnitId:deps[0].id,owner});}
const aliases=new Map(targets.filter(t=>t.name.split(' ').length>2).map(t=>[norm(t.name.split(' ')[0]),norm(t.name)]));aliases.set('jocelei medeiros dos reis','asfalto ii');
const targetFor=name=>targets.find(t=>norm(t.name)===(aliases.get(norm(name))||norm(name)));
let moved=0,linked=0;const pending=[];
for(const e of employees){const old=d.companyGroupEmployeeAssignments.find(a=>a.groupId===group.id&&a.employeeId===e.id);const source=d.teams.find(t=>t.id===e.teamId);const assigned=units.find(u=>u.id===old?.teamUnitId);const target=targetFor(source?.name||assigned?.name);if(!target){if(e.teamId)pending.push({name:e.name,team:source?.name||e.teamId});continue;}const deps=d.departments.filter(dep=>dep.companyId===e.companyId&&norm(dep.name)===norm(target.department)&&dep.active!==false);if(deps.length!==1)throw new Error('Departamento ausente: '+e.name);const oldDep=d.departments.find(dep=>dep.id===e.departmentId);const changedDept=oldDep&&norm(oldDep.name)!==norm(target.department);if(changedDept)moved++;set('employees',e.id,{teamId:target.sourceId,departmentId:deps[0].id,groupId:group.id,isTeamLead:e.id===target.owner,...(changedDept?{sectorId:'',subsectorId:''}:{})});set('companyGroupEmployeeAssignments',old?.id||group.id+'-'+e.id,{groupId:group.id,employeeId:e.id,departmentUnitId:target.departmentUnitId,teamUnitId:target.id,sectorUnitId:changedDept?'':old?.sectorUnitId||'',subsectorUnitId:changedDept?'':old?.subsectorUnitId||''});linked++;}
const targetIds=new Set(targets.map(t=>t.id));const retired=new Set();
for(const u of units.filter(u=>u.type==='team'&&!targetIds.has(u.id))){const matching=targetFor(u.name);const finalAssignments=d.companyGroupEmployeeAssignments.filter(a=>a.groupId===group.id).map(a=>changes.get('companyGroupEmployeeAssignments/'+a.id)?.after||a);const inUse=finalAssignments.some(a=>a.teamUnitId===u.id);if(matching||norm(u.name)==='asfalto'||norm(u.name)==='wilson'){if(inUse)throw new Error('Equipe antiga ainda vinculada: '+u.name);if(norm(u.name)==='wilson'){del('companyGroupUnits',u.id);for(const link of d.companyGroupUnitLinks.filter(l=>l.unitId===u.id))del('companyGroupUnitLinks',link.id);}else set('companyGroupUnits',u.id,{active:false,coordinatorEmployeeId:''});retired.add(u.id);}}
for(const old of d.companyGroupLeadershipAssignments.filter(a=>a.groupId===group.id&&a.role==='lider'&&(targetIds.has(a.unitId)||retired.has(a.unitId)))){const target=targets.find(t=>t.id===old.unitId);if(!target?.owner||old.id!==`group-unit-responsible-${target.id}-lider`||old.employeeId!==target.owner)del('companyGroupLeadershipAssignments',old.id);}
for(const t of targets){if(t.owner){const assignment=[...changes.values()].find(c=>c.collection==='companyGroupEmployeeAssignments'&&c.after?.employeeId===t.owner)?.after||d.companyGroupEmployeeAssignments.find(a=>a.groupId===group.id&&a.employeeId===t.owner);if(assignment?.teamUnitId!==t.id)throw new Error('Responsavel fora da equipe: '+t.name);set('companyGroupLeadershipAssignments',`group-unit-responsible-${t.id}-lider`,{groupId:group.id,unitId:t.id,employeeId:t.owner,role:'lider'});}}
for(const e of employees){const wasOwner=units.some(u=>u.type==='team'&&u.coordinatorEmployeeId===e.id&&(targetIds.has(u.id)||retired.has(u.id)));if(wasOwner&&!targets.some(t=>t.owner===e.id))set('employees',e.id,{isTeamLead:false});}
const plan=[...changes.values()];fs.writeFileSync("group-teams-revision-plan.local",JSON.stringify(plan));console.log(JSON.stringify({teams:targets.length,leaders:targets.filter(t=>t.owner).length,examinedEmployees:linked,changedDepartments:moved,operations:plan.length,deactivatedTeams:plan.filter(c=>c.collection==='companyGroupUnits'&&c.before?.active!==false&&c.after?.active===false).length,changedEmployees:plan.filter(c=>c.collection==='employees').length,changedMemberships:plan.filter(c=>c.collection==='companyGroupEmployeeAssignments').length,preservedUnlisted:pending},null,2));
if(process.argv.includes('--apply')){const backup=`group-teams-revision-${Date.now()}.local`;fs.writeFileSync(backup,JSON.stringify(plan,null,2),{flag:'wx'});const env=Object.fromEntries(fs.readFileSync('.env','utf8').split(/\r?\n/).filter(l=>l.includes('=')&&!l.trim().startsWith('#')).map(l=>{const i=l.indexOf('=');return[l.slice(0,i).trim(),l.slice(i+1).trim().replace(/^['"]|['"]$/g,'')]}));const app=initializeApp({apiKey:env.VITE_FIREBASE_API_KEY,projectId:env.VITE_FIREBASE_PROJECT_ID});try{const db=getFirestore(app);for(let i=0;i<plan.length;i+=150){const chunk=plan.slice(i,i+150);await runTransaction(db,async tx=>{const snapshots=await Promise.all(chunk.map(c=>tx.get(doc(db,c.collection,c.id))));snapshots.forEach((s,n)=>{if(!isDeepStrictEqual(s.exists()?{...s.data(),id:s.id}:null,chunk[n].before))throw new Error('Alteracao concorrente '+s.id)});chunk.forEach(c=>c.after?tx.set(doc(db,c.collection,c.id),c.after):tx.delete(doc(db,c.collection,c.id)));});console.log(`Gravados ${Math.min(i+150,plan.length)}/${plan.length}`);}for(let i=0;i<plan.length;i+=40)await Promise.all(plan.slice(i,i+40).map(async c=>{const s=await getDocFromServer(doc(db,c.collection,c.id));if(!isDeepStrictEqual(s.exists()?{...s.data(),id:s.id}:null,c.after))throw new Error('Falha verificacao '+c.id)}));console.log('Backup: '+backup+'; todos os documentos verificados.');}finally{await deleteApp(app)}}
