import fs from 'node:fs';
import {initializeApp,deleteApp} from 'firebase/app';
import {getFirestore,doc,runTransaction,getDocFromServer} from 'firebase/firestore';
const data=JSON.parse(fs.readFileSync('group-teams-current.local','utf8'));
const group=data.companyGroups.find(g=>g.name==='Grupo Macro');
const target=data.companyGroupUnits.find(u=>u.groupId===group.id&&u.name==='Marconi Modesto da Silva'&&u.parentUnitId==='suggested-department-producao');
if(!target)throw new Error('Equipe destino ausente');
const names=['CRISTIANO DA SILVA SANTANA','EDERSON PEREIRA SOARES'];
const pairs=names.map(name=>{const es=data.employees.filter(e=>e.name===name&&e.groupId===group.id);if(es.length!==1)throw new Error('Funcionario ambiguo');const e=es[0];const a=data.companyGroupEmployeeAssignments.find(a=>a.employeeId===e.id&&a.groupId===group.id);const dep=data.departments.find(d=>d.companyId===e.companyId&&d.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'')==='Producao'&&d.active!==false);if(!a||!dep)throw new Error('Vinculo ausente');return {e,a,dep};});
const env=Object.fromEntries(fs.readFileSync('.env','utf8').split(/\r?\n/).filter(l=>l.includes('=')&&!l.trim().startsWith('#')).map(l=>{const i=l.indexOf('=');return[l.slice(0,i).trim(),l.slice(i+1).trim().replace(/^['"]|['"]$/g,'')]}));
const app=initializeApp({apiKey:env.VITE_FIREBASE_API_KEY,projectId:env.VITE_FIREBASE_PROJECT_ID});
try{const db=getFirestore(app);const paths=[['companyGroupUnits',target.id],['teams','source-'+target.id],...pairs.flatMap(({e,a,dep})=>[['employees',e.id],['companyGroupEmployeeAssignments',a.id],['departments',dep.id]])];const refs=paths.map(([c,id])=>doc(db,c,id));const backup=`asfalto-marconi-backup-${Date.now()}.local`;
await runTransaction(db,async tx=>{const snaps=await Promise.all(refs.map(r=>tx.get(r)));if(snaps.some(s=>!s.exists()))throw new Error('Registro ausente');const live=snaps.map(s=>s.data());if(live[0].active===false||live[0].parentUnitId!==target.parentUnitId)throw new Error('Destino mudou');const patches=[];pairs.forEach(({e,a,dep},i)=>{const n=2+i*3;const employee=live[n],assignment=live[n+1];if(employee.teamId!==e.teamId||employee.companyId!==e.companyId||employee.groupId!==group.id||assignment.teamUnitId!==a.teamUnitId||employee.isTeamLead)throw new Error('Vinculo mudou; revisar');if(!e.teamId.endsWith('-asfalto'))throw new Error('Origem diferente de Asfalto');const moved=employee.departmentId!==dep.id;const now=new Date().toISOString();patches.push([n,{teamId:'source-'+target.id,departmentId:dep.id,updatedAt:now,...(moved?{sectorId:'',subsectorId:''}:{})}],[n+1,{teamUnitId:target.id,departmentUnitId:target.parentUnitId,updatedAt:now,...(moved?{sectorUnitId:'',subsectorUnitId:''}:{})}]);});fs.writeFileSync(backup,JSON.stringify(patches.map(([n,patch])=>({path:paths[n],before:live[n],patch})),null,2));for(const[n,patch]of patches)tx.update(refs[n],patch);});
for(const {e,a,dep}of pairs){const [employee,assignment]=await Promise.all([getDocFromServer(doc(db,'employees',e.id)),getDocFromServer(doc(db,'companyGroupEmployeeAssignments',a.id))]);if(employee.data().teamId!=='source-'+target.id||employee.data().departmentId!==dep.id||assignment.data().teamUnitId!==target.id)throw new Error('Verificacao falhou');console.log(e.name+' -> Marconi Modesto da Silva / Producao: confirmado');}console.log('Backup: '+backup);
}finally{await deleteApp(app)}
